In [100]:
import numpy as np  

#NumPy（Numerical Python）是一个开源的Python库，提供了高性能的多维数组对象和用于处理数组的函数。
#它是许多科学计算和数据分析任务的基础库之一。

In [101]:
### 数组
## 创建数组
# 使用np.array直接创建
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [102]:
# 使用np.ones、np.zeros创建全1或全0数组
np.ones(5)

array([1., 1., 1., 1., 1.])

In [103]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [104]:
## 数组运算（加减乘除等）
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,2,2,2,2])
print(arr1)
print(arr2)


[1 2 3 4 5]
[2 2 2 2 2]


In [105]:
#数组相加
arr3 = arr1 + arr2
arr3

array([3, 4, 5, 6, 7])

In [106]:
#数组相乘法
arr4 = arr1 * arr2
arr4

array([ 2,  4,  6,  8, 10])

In [107]:
#数组乘以整数(本质上是数组想成的特例)
arr5 = arr1 * 2
arr5

array([ 2,  4,  6,  8, 10])

In [108]:
## 数组索引，跟python索引一致
arr1 = np.array([1,2,5,7,9,11])
arr1


array([ 1,  2,  5,  7,  9, 11])

In [109]:
#输出第1个元素
arr1[0] 

1

In [110]:
#输出最后1个元素
arr1[-1]

11

In [111]:
#输出索引2-4的元素（左闭右开）
arr1[2:4]


array([5, 7])

In [112]:
#输出索引3及之前的所有元素（左闭右开）
arr1[:3]#输出索引3及之前的所有元素（左闭右开）


array([1, 2, 5])

In [113]:
#输出索引3及之后的所有元素
arr1[3:]

array([ 7,  9, 11])

In [114]:
## 数组聚合
arr1 = np.array([1,2,5,7,9,11])
arr1



array([ 1,  2,  5,  7,  9, 11])

In [115]:
#求数组最大值
arr1.max()

11

In [116]:
#求数组最小值
arr1.min()

1

In [117]:
#数组求和
arr1.sum()

35

In [118]:
#求数组均值
arr1.mean()

5.833333333333333

In [119]:
### 矩阵

##创建矩阵
#使用np.array直接创建
np.array([[1,2,3,],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
# 使用np.ones、np.zeros创建全1或全0矩阵
np.ones((3,3))  #创建3行3列矩阵

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
np.zeros((3,3))  #创建3行3列矩阵

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [122]:
## 矩阵运算
arr1 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
arr2 = np.array([[1,1,1,],[2,2,2],[3,3,3]])
print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [123]:
#矩阵相加（对应索引元素相加）
arr3 = arr1 + arr2
arr3


array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [124]:

#矩阵相乘（对应索引元素相乘）
arr4 = arr1 * arr2
arr4

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [125]:
## 矩阵点积（线性代数）
arr1 = np.array([[1,2,],[4,5],[7,8]])
arr2 = np.array([[1,1,1,],[2,2,2]])
print(arr1)
print(arr2,'\n')

#矩阵点积
arr3 = arr1.dot(arr2)
print(arr3)


[[1 2]
 [4 5]
 [7 8]]
[[1 1 1]
 [2 2 2]] 

[[ 5  5  5]
 [14 14 14]
 [23 23 23]]


In [126]:
## 矩阵索引
# 第一个索引取行，第二个索引取列
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
arr1


array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [127]:
#输出第0行第1列元素
arr1[0,1]


2

In [128]:
#输出第1行所有元素
arr1[1]

array([4, 5, 6, 7])

In [129]:
#输出第1列所有元素
arr1[:,1]

array([ 2,  5,  8, 11])

In [130]:
#输出第2到第4行所有元素
arr1[2:4]

array([[ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [131]:
#输出第2到第4列所有元素
arr1[:,2:4]

array([[ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [132]:
#输出第2到第4行&第2到第4列元素
arr1[2:4,2:4]

array([[ 9, 10],
       [12, 13]])

In [133]:
## 矩阵聚合

#矩阵全部聚合
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
print(arr1.max())  #求矩阵最大值
print(arr1.min())  #求矩阵最小值
print(arr1.sum())  #矩阵求和
print(arr1.mean())  #求矩阵均值


13
1
112
7.0


In [134]:
#矩阵按行列聚合（参考按数组聚合）
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
print('arr1=',arr1,'\n')

print(arr1[1].max())  #求矩阵第1行最大值
print(arr1[:,1].max())  #求矩阵第1列最大值


arr1= [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]] 

7
11


In [135]:
## 矩阵转置（线性代数）
arr1 = np.array([[1,2,3,4],[4,5,6,7]])
print('arr1=',arr1,'\n')

arr2 = arr1.T
print('arr1=',arr2,'\n')

arr1= [[1 2 3 4]
 [4 5 6 7]] 

arr1= [[1 4]
 [2 5]
 [3 6]
 [4 7]] 



In [136]:
## 矩阵重塑
# 查看矩阵维度
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
arr1.shape

(4, 4)

In [137]:
#将4行4列的矩阵重塑为2行8列
arr2 = arr1.reshape(2,8)
print(arr2,'\n')
print(arr2.shape)

[[ 1  2  3  4  4  5  6  7]
 [ 7  8  9 10 10 11 12 13]] 

(2, 8)


In [138]:
## 高纬数组
# 例如构建3维数值
arr1 = np.array([[[1,2],[3,4]],[[4,5],[6,7]],[[7,8],[9,10]],[[10,11],[12,13]]])
arr1


array([[[ 1,  2],
        [ 3,  4]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 7,  8],
        [ 9, 10]],

       [[10, 11],
        [12, 13]]])

In [139]:
arr1.shape

(4, 2, 2)

In [140]:
## 参考文档：
#1) https://numpy.org/doc/stable/user/index.html
#2) https://zhuanlan.zhihu.com/p/81815234