In [2]:
import numpy as np  

#NumPy（Numerical Python）是一个开源的Python库，提供了高性能的多维数组对象和用于处理数组的函数。
#它是许多科学计算和数据分析任务的基础库之一。

In [22]:
### 数组
## 创建数组
# 使用np.array直接创建
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
# 使用np.ones、np.zeros创建全1或全0数组
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
## 数组运算（加减乘除等）
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,2,2,2,2])
print('arr1=',arr1)
print('arr2=',arr2,'\n')

#数组相加
arr3 = arr1 + arr2
print('arr3=',arr3)

#数组相乘法
arr4 = arr1 * arr2
print('arr4=',arr4)

#数组乘以整数(本质上是数组想成的特例)
arr5 = arr1 * 3
print('arr5=',arr5)

arr1= [1 2 3 4 5]
arr2= [2 2 2 2 2] 

arr3= [3 4 5 6 7]
arr4= [ 2  4  6  8 10]
arr5= [ 3  6  9 12 15]


In [16]:
## 数组索引，跟python索引一致
arr1 = np.array([1,2,5,7,9,11])
print(arr1,'\n')
print(arr1[0]) #输出第1个元素
print(arr1[-1]) #输出最后1个元素
print(arr1[2:4]) #输出索引2-4的元素（左闭右开）
print(arr1[:3]) #输出索引3及之前的所有元素（左闭右开）
print(arr1[3:]) #输出索引3及之后的所有元素


[ 1  2  5  7  9 11] 

1
11
[5 7]
[1 2 5]
[ 7  9 11]


In [21]:
## 数组聚合
arr1 = np.array([1,2,5,7,9,11])
print(arr1,'\n')

#求数组最大值
arr1_max = arr1.max()
print(arr1_max)

#求数组最小值
arr1_min = arr1.min()
print(arr1_min)

#数组求和
arr1_sum = arr1.sum()
print(arr1_sum)

#求数组均值
arr1_mean = arr1.mean()
print(arr1_mean)

[ 1  2  5  7  9 11] 

11
1
35
5.833333333333333


In [25]:
### 矩阵

##创建矩阵
#使用np.array直接创建
np.array([[1,2,3,],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
## 使用np.ones、np.zeros创建全1或全0矩阵

In [27]:
np.ones((3,3))  #创建3行3列矩阵

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.zeros((3,3))  #创建3行3列矩阵

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
## 矩阵运算
arr1 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
arr2 = np.array([[1,1,1,],[2,2,2],[3,3,3]])
print('arr1=',arr1)
print('arr2=',arr2,'\n')

#矩阵相加（对应索引元素相加）
arr3 = arr1 + arr2
print('arr3=',arr3)

#矩阵相乘（对应索引元素相乘）
arr4 = arr1 * arr2
print('arr4=',arr4)

arr1= [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2= [[1 1 1]
 [2 2 2]
 [3 3 3]] 

arr3= [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
arr4= [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [37]:
# 矩阵点击（线性代数）
arr1 = np.array([[1,2,],[4,5],[7,8]])
arr2 = np.array([[1,1,1,],[2,2,2]])
print('arr1=',arr1)
print('arr2=',arr2,'\n')

arr3 = arr1.dot(arr2)
print('arr3=',arr3)

arr1= [[1 2]
 [4 5]
 [7 8]]
arr2= [[1 1 1]
 [2 2 2]] 

arr3= [[ 5  5  5]
 [14 14 14]
 [23 23 23]]


In [44]:
## 矩阵索引
# 第一个索引取行，第二个索引取列
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
print('arr1=',arr1,'\n')

print(arr1[0,1],'\n') #输出第0行第1列元素

print(arr1[1],'\n') #输出第1行所有元素
print(arr1[:,1],'\n') #输出第1列所有元素

print(arr1[2:4],'\n') #输出第2到第4行所有元素
print(arr1[:,2:4],'\n') #输出第2到第4列所有元素

print(arr1[2:4,2:4],'\n') #输出第2到第4行&第2到第4列元素

arr1= [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]] 

2 

[4 5 6 7] 

[ 2  5  8 11] 

[[ 7  8  9 10]
 [10 11 12 13]] 

[[ 3  4]
 [ 6  7]
 [ 9 10]
 [12 13]] 

[[ 9 10]
 [12 13]] 



In [48]:
## 矩阵聚合

#矩阵全部聚合
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
print(arr1.max())  #求矩阵最大值
print(arr1.min())  #求矩阵最小值
print(arr1.sum())  #矩阵求和
print(arr1.mean())  #求矩阵均值


13
1
112
7.0


In [50]:
#矩阵按行列聚合（参考按数组聚合）
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
print('arr1=',arr1,'\n')

print(arr1[1].max())  #求矩阵第1行最大值
print(arr1[:,1].max())  #求矩阵第1列最大值


arr1= [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]] 

7
11


In [53]:
## 矩阵转置（线性代数）
arr1 = np.array([[1,2,3,4],[4,5,6,7]])
print('arr1=',arr1,'\n')

arr2 = arr1.T
print('arr1=',arr2,'\n')

arr1= [[1 2 3 4]
 [4 5 6 7]] 

arr1= [[1 4]
 [2 5]
 [3 6]
 [4 7]] 



In [56]:
## 矩阵重塑
# 查看矩阵维度
arr1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]])
arr1.shape

(4, 4)

In [59]:
#将4行4列的矩阵重塑为2行8列
arr2 = arr1.reshape(2,8)
print(arr2,'\n')
print(arr2.shape)

[[ 1  2  3  4  4  5  6  7]
 [ 7  8  9 10 10 11 12 13]] 

(2, 8)


In [62]:
## 高纬数组
# 例如构建3维数值
arr1 = np.array([[[1,2],[3,4]],[[4,5],[6,7]],[[7,8],[9,10]],[[10,11],[12,13]]])
arr1


array([[[ 1,  2],
        [ 3,  4]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 7,  8],
        [ 9, 10]],

       [[10, 11],
        [12, 13]]])

In [63]:
arr1.shape

(4, 2, 2)